esphome:
  name: esp32-bt-proxy
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Restart (Safe Mode)
    entity_category: diagnostic

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
