esphome:
  name: esp32c3-bt-proxy
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
  on_boot:
    priority: 250
    then:
      - delay: 15s
      - lambda: |-
          id(ble_tracker).set_scan_continuous(true); 
          id(ble_tracker).start_scan();

esp32:
  variant: ESP32C3
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

logger:
  level: DEBUG

api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: true
    continuous: false
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Restart (Safe Mode)
    entity_category: diagnostic

